import { useEffect, useMemo, useState } from 'react'
import '../styles/utilities.css'

const api = import.meta.env.VITE_API_URL
const authHeaders = () => ({ Authorization: `Bearer ${localStorage.getItem('posToken')}` })

export function MarketingCenter() {
  const [campaigns, setCampaigns] = useState([]); const [customers, setCustomers] = useState([]); const [form, setForm] = useState({ title: '', message: '', audience: 'All customers' }); const [notice, setNotice] = useState('')
  const load = async () => { const [c, u] = await Promise.all([fetch(`${api}/api/campaigns`, { headers: authHeaders() }), fetch(`${api}/api/customers`, { headers: authHeaders() })]); if (c.ok) setCampaigns(await c.json()); if (u.ok) setCustomers(await u.json()) }
  useEffect(() => { load().catch(() => setNotice('Could not load marketing data.')) }, [])
  const save = async (sendNow) => { try { const r = await fetch(`${api}/api/campaigns`, { method: 'POST', headers: { ...authHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, sendNow }) }); const body = await r.json(); if (!r.ok) throw new Error(body.message); setCampaigns((x) => [body, ...x]); setForm({ title: '', message: '', audience: 'All customers' }); setNotice(sendNow ? 'Campaign marked as sent.' : 'Message saved as a draft.') } catch (e) { setNotice(e.message || 'Could not save campaign.') } }
  return <UtilityLayout title="Marketing Center" description="Create promotions, prepare customer messages, and keep a campaign history."><section className="utility-card"><h2>Create promotion or message</h2><div className="utility-grid"><label>Campaign name<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Weekend special" /></label><label>Audience<select value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })}><option>All customers</option><option>Selected customers</option><option>Customer group</option></select></label><label className="wide">Message<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Write your promotion or customer message…" /></label></div><p className="utility-muted">{customers.length} customers available for messaging. Delivery integrations can be connected later.</p><div className="utility-actions"><button type="button" className="secondary" onClick={() => save(false)}>Save draft</button><button type="button" onClick={() => save(true)}>Mark as sent</button></div></section><section className="utility-card"><h2>Campaign & message history</h2>{campaigns.length ? <div className="utility-list">{campaigns.map((x) => <div key={x._id}><strong>{x.title}</strong><span>{x.audience} · {x.status} · {new Date(x.createdAt).toLocaleDateString()}</span></div>)}</div> : <Empty text="No campaigns yet." />}</section>{notice && <p className="utility-notice">{notice}</p>}</UtilityLayout>
}

export function CustomerTools() {
  const [customers, setCustomers] = useState([]); const [form, setForm] = useState({ name: '', phone: '', email: '', group: 'General', tags: '' }); const [notice, setNotice] = useState('')
  const load = async () => { const r = await fetch(`${api}/api/customers`, { headers: authHeaders() }); if (r.ok) setCustomers(await r.json()) }; useEffect(() => { load().catch(() => {}) }, [])
  const add = async (e) => { e.preventDefault(); const r = await fetch(`${api}/api/customers`, { method: 'POST', headers: { ...authHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, tags: form.tags.split(',').map((x) => x.trim()).filter(Boolean) }) }); const body = await r.json(); if (!r.ok) return setNotice(body.message || 'Could not add customer'); setCustomers((x) => [body, ...x]); setForm({ name: '', phone: '', email: '', group: 'General', tags: '' }); setNotice('Customer added.') }
  const exportCustomers = () => { const rows = [['Name', 'Phone', 'Email', 'Group', 'Tags'], ...customers.map((x) => [x.name, x.phone, x.email, x.group, (x.tags || []).join(';')])]; const blob = new Blob([rows.map((r) => r.map((x) => `"${String(x || '').replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'customers.csv' }); link.click(); URL.revokeObjectURL(link.href) }
  return <UtilityLayout title="Customer Tools" description="Import or export customer data and organize customers with groups and tags."><section className="utility-card"><h2>Add customer</h2><form onSubmit={add} className="utility-grid"><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Email<input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Group<input value={form.group} onChange={(e) => setForm({ ...form, group: e.target.value })} /></label><label className="wide">Tags (comma separated)<input value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} placeholder="VIP, wholesale" /></label><div className="utility-actions wide"><button>Add customer</button><button type="button" className="secondary" onClick={exportCustomers}>Export customers</button></div></form></section><section className="utility-card"><h2>Customers ({customers.length})</h2>{customers.length ? <div className="utility-list">{customers.map((x) => <div key={x._id}><strong>{x.name}</strong><span>{x.group || 'General'} · {(x.tags || []).join(', ') || 'No tags'} · {x.phone || x.email || 'No contact details'}</span></div>)}</div> : <Empty text="Add customers here or import them through the API." />}</section>{notice && <p className="utility-notice">{notice}</p>}</UtilityLayout>
}

export function InventoryUtilities() {
  const [products, setProducts] = useState([]); const [selected, setSelected] = useState(''); const [quantity, setQuantity] = useState(''); const [notice, setNotice] = useState(''); const selectedProduct = useMemo(() => products.find((x) => x._id === selected), [products, selected])
  const load = async () => { const r = await fetch(`${api}/api/products`); if (r.ok) setProducts(await r.json()) }; useEffect(() => { load().catch(() => {}) }, [])
  const adjust = async (e) => { e.preventDefault(); if (!selectedProduct) return setNotice('Select a product.'); const amount = Number(quantity); if (!Number.isFinite(amount)) return setNotice('Enter a valid final stock count.'); const r = await fetch(`${api}/api/products/${selected}`, { method: 'PATCH', headers: { ...authHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ stock: amount }) }); const body = await r.json(); if (!r.ok) return setNotice(body.message || 'Could not update stock'); setProducts((x) => x.map((p) => p._id === body._id ? body : p)); setNotice(`${body.name} stock updated to ${body.stock}.`); setQuantity('') }
  const exportInventory = () => { const rows = [['Name', 'SKU', 'Stock', 'Minimum stock', 'Cost', 'Price'], ...products.map((x) => [x.name, x.sku, x.stock, x.minStock, x.cost, x.price])]; const blob = new Blob([rows.map((r) => r.join(',')).join('\n')], { type: 'text/csv' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'inventory.csv' }); link.click(); URL.revokeObjectURL(link.href) }
  return <UtilityLayout title="Inventory Utilities" description="Perform stock counts, corrections, exports, and product maintenance tasks."><section className="utility-card"><h2>Stock adjustment / count</h2><form onSubmit={adjust} className="utility-grid"><label>Product<select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Select product</option>{products.map((x) => <option key={x._id} value={x._id}>{x.name} ({x.stock} in stock)</option>)}</select></label><label>Final stock count<input type="number" min="0" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></label><div className="utility-actions wide"><button>Save stock count</button><button type="button" className="secondary" onClick={exportInventory}>Export inventory</button></div></form></section><section className="utility-card"><h2>Bulk maintenance</h2><div className="utility-list"><div><strong>Bulk product import</strong><span>Use the products API to import validated product data in batches.</span></div><div><strong>Barcode generation</strong><span>Use each product SKU as its barcode value; printable barcode labels can be added next.</span></div></div></section>{notice && <p className="utility-notice">{notice}</p>}</UtilityLayout>
}

function UtilityLayout({ title, description, children }) { return <main className="utilities-page"><header><span>UTILITIES</span><h1>{title}</h1><p>{description}</p></header>{children}</main> }
function Empty({ text }) { return <p className="utility-muted">{text}</p> }
